apiVersion: v1
kind: Secret
metadata:
  name: viewer-config
type: kubernetes.io/basic-auth
stringData:
  username: viewer
  password: {{ randAlphaNum 16 }}
  roles: viewer
---
apiVersion: v1
kind: Secret
metadata:
  name: editor-config
type: kubernetes.io/basic-auth
stringData:
  username: editor
  password: {{ randAlphaNum 16 }}
  roles: editor
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.6.0
  auth:
    fileRealm:
      - secretName: viewer-config
      - secretName: editor-config
  nodeSets:
    - name: default
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: gp2
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  config:
    xpack.apm.ui.maxTraceItems: 10000
  version: 8.6.0
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: quickstart
  namespace: default
spec:
  version: 8.6.0
  count: 3
  elasticsearchRef:
    name: quickstart
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-opentelemetry
spec:
  mode: daemonset
  config: |
    exporters:
      logging: {}
      otlp/elastic:
        endpoint: "quickstart-apm-http:8200"
        headers:
          # Elastic APM Server secret token
          Authorization: "Bearer ${secret-token}"
        tls:
          insecure_skip_verify: true

    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check: {}
      memory_ballast: {}
    processors:
      batch:
        timeout: 10s
        send_batch_size: 10000
        send_batch_max_size: 11000
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        limit_percentage: 50
        spike_limit_percentage: 30

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins: ["*"]
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:
          exporters:
            - logging
            - otlp/elastic
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        traces:
          exporters:
            - logging
            - otlp/elastic
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
  envFrom:
    - secretRef:
        name: quickstart-apm-token
