{{- $elasticPassword := randAlphaNum 16 -}}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-default-config
type: kubernetes.io/basic-auth
stringData:
  username: elastic
  password: {{ $elasticPassword }}
  roles: superuser
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.6.0
  auth:
    fileRealm:
    - secretName: elastic-default-config
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.6.0
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-opentelemetry
spec:
  mode: daemonset
  config: |
    exporters:
      logging: {}
      elasticsearch/trace:
        endpoints: [https://quickstart-es-http:9200]
        traces_index: trace_index
        user: ${username}
        password: ${password}
        tls:
          insecure_skip_verify: true
      elasticsearch/log:
        endpoints: [https://quickstart-es-http:9200]
        logs_index: my_log_index
        user: ${username}
        password: ${password}
        tls:
          insecure_skip_verify: true

    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check: {}
      memory_ballast: {}
    processors:
      batch:
        timeout: 10s
        send_batch_size: 10000
        send_batch_max_size: 11000
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        limit_percentage: 50
        spike_limit_percentage: 30

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${MY_POD_IP}:8888
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:
          exporters:
            - logging
            - elasticsearch/log
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - logging
            - elasticsearch/trace
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - zipkin
  envFrom:
  - secretRef:
      name: elastic-default-config
