apiVersion: v1
kind: Secret
metadata:
  name: elastic-config
data:
  ES_USERNAME: ZWxhc3RpYwo=
  ES_PASSWORD:  {{ index (lookup "v1" "Secret" .Release.Namespace "quickstart-es-elastic-user").data "elastic" }}
