apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
data:
  elastic_user: elastic

apiVersion: v1
kind: Secret
metadata:
  name: elastic-config
data:
  ES_USERNAME: ZWxhc3RpYwo=
  ES_PASSWORD:  {{ (lookup "v1" "Secret" .Release.Namespace "quickstart-es-elastic-user").data "elastic" }}
