apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  tls:
  - hosts:
    - {{ .Values.kibanaHost }}
    secretName: "{{ .Values.kibanaHost }}-secret-tls"
  rules:
    - host: {{ .Values.kibanaHost }}
      http:
        paths:
          - backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601
            path: /
            pathType: Prefix
