apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-opentelemetry
spec:
  mode: deployment # This configuration is omittable.
  config: |
    exporters:
      logging: {}
      jaeger:
        endpoint: jaeger-collector.observability:14250
        tls:
          insecure: true
      elasticsearch/trace:
        endpoints: [https://quickstart-es-http:9200]
        traces_index: trace_index
        user: {{ .Values.elasticCredentials.user }}
        password: ${elastic}
        tls:
          insecure_skip_verify: true
      elasticsearch/log:
        endpoints: [https://quickstart-es-http:9200]
        logs_index: my_log_index
        user: {{ .Values.elasticCredentials.user }}
        password: ${elastic}
        tls:
          insecure_skip_verify: true

    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check: {}
      memory_ballast: {}
    processors:
      batch: {}
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30

    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${MY_POD_IP}:8888
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:
          exporters:
            - logging
            - elasticsearch/log
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - logging
            - elasticsearch/trace
            - jaeger
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - jaeger
            - zipkin
  envFrom:
  - secretRef:
      name: quickstart-es-elastic-user

