apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: prometheus
type: Opaque
data:
  username: {{ .Values.prometheus.user |  b64enc | quote }}
  password: {{ .Values.prometheus.password |  b64enc | quote }}
