# Default values for tce-boot-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
fullName: tce-boot-node

ports:
  http: 8080
  p2p: 9090

image:
  repository: ghcr.io/toposware/topos
  tag: pr-80

global:
  credentials:
    username: nobody
    password: secret
