{{ if not .Values.remoteCluster }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared
spec:
  storageClassName: efs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{ end }}
