{{ if .Values.certSpammer }}
{{ $spammer := lookup "apps/v1" "Deployment" .Release.Namespace "cert-spammer" }}
{{ if not $spammer }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mode }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-spammer
  labels:
    app: cert-spammer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-spammer
  template:
    metadata:
      labels:
        app: cert-spammer
    spec:
      imagePullSecrets:
        - name: {{ .Values.mode }}-pull-secret
      containers:
        - name: spam
          image: ghcr.io/toposware/cert-spammer:main
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/shared
              name: shared
          env:
            - name: RUST_LOG
              value: info
            - name: CERT_PER_BATCH
              value: "1"
            - name: BATCH_TIME_INTERVAL
              value: "4"
            - name: TARGET_NODES_PATH
              value: /tmp/shared/peer_nodes.json
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared
{{ end }}
{{ end }}
