apiVersion: v1
kind: Service
metadata:
  name: boot
  labels:
    app: boot
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ports.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: boot
  sessionAffinity: ClientIP
