{{ if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.mode }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-{{ .Values.acme.environment }}"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: "{{ .Values.host }}-secret-tls"
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Values.mode }}
                port:
                  number: 1340
            path: /
            pathType: Prefix
{{ end }}
