{{- range $index, $e := until (int $.Values.peerReplicas) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-{{ $index }}
  labels:
    app: peer-{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer-{{ $index }}
  template:
    metadata:
      labels:
        app: peer-{{ $index }}
        node: peer
    spec:
      hostname: peer-{{ $index }}
      imagePullSecrets:
        - name: {{ $.Chart.Name }}-pull-secret
      containers:
        - name: peer
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          args: ["tce", "run"]
          imagePullPolicy: Always
          ports:
            - name: p2p
              containerPort: {{ $.Values.ports.p2p }}
              protocol: TCP
            - name: http
              containerPort: {{ $.Values.ports.http }}
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/shared
              name: shared
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - /tmp/liveness.sh
                - peer
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: LOCAL_TEST_NET
              value: "true"
            - name: RUST_LOG
              value: info,topos_p2p=debug,topos_tce_node_app=debug,topos_tce_protocols_reliable_broadcast=debug
            - name: TCE_DB_PATH
              value: /tmp/default-db
            - name: TCE_API_ADDR
              value: 0.0.0.0:1340
            - name: TCE_JAEGER_SERVICE_NAME
              value: tce-regular-node
            - name: TCE_JAEGER_AGENT
              value: {{ $.Values.otelEndpoint }}
            - name: TCE_BOOT_PEERS
              value: "12D3KooWRhFCXBhmsMnur3up3vJsDoqWh4c39PKXgSWwzAzDHNLn /dns4/boot/tcp/{{ $.Values.ports.p2p }}"
            - name: TCE_ECHO_SAMPLE_SIZE
              value: "3"
            - name: TCE_READY_SAMPLE_SIZE
              value: "3"
            - name: TCE_DELIVERY_SAMPLE_SIZE
              value: "3"
            - name: TCE_ECHO_THRESHOLD
              value: "3"
            - name: TCE_READY_THRESHOLD
              value: "3"
            - name: TCE_DELIVERY_THRESHOLD
              value: "3"
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared
{{- end }}
